import { createContext, useContext, ReactNode } from "react";

interface LanguageContextType {
  t: (key: string) => any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const t = (key: string): any => {
    const keys = key.split(".");
    let value: any = translations;
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

// Vietnamese translations only
const translations = {
  nav: {
    home: "Trang chủ",
    solutions: "Giải pháp",
    projects: "Dự án",
    lab: "Ninja Lab",
    about: "Về chúng tôi",
    applyLab: "Ứng tuyển Lab",
  },
  home: {
    hero: {
      badge: "Đối tác triển khai AI • Việt Nam",
      title: "Xây dựng",
      titleHighlight: "Hệ thống AI",
      titleEnd: "Chuyển đổi Doanh nghiệp",
      description: "Từ AI agents và nền tảng ERP đến tự động hóa toàn diện và hệ thống agentic — Ninja AI triển khai giải pháp thực tế mang lại kết quả đo lường được cho doanh nghiệp hiện đại.",
      exploreSolutions: "Khám phá Giải pháp",
      viewProjects: "Xem Dự án",
    },
    metrics: {
      projects: "Dự án",
      deploy: "Triển khai",
      builders: "Builders",
      avgEfficiency: "Hiệu suất TB",
      costReduction: "Giảm Chi phí",
      processAuto: "Tự động hóa",
      systemsDeployed: "Hệ thống Triển khai",
    },
    byTheNumbers: {
      subtitle: "Con số Thực tế",
      title: "Tác động Đo lường được",
      clients: { value: "50+", label: "Khách hàng Doanh nghiệp", desc: "Tin tưởng hệ thống của chúng tôi" },
      systems: { value: "120+", label: "Hệ thống Triển khai", desc: "Đang chạy production" },
      uptime: { value: "99.8%", label: "Uptime Trung bình", desc: "Độ tin cậy hệ thống" },
      roi: { value: "3.5×", label: "ROI Trung bình", desc: "Trong 12 tháng đầu" },
    },
    howWeWork: {
      subtitle: "Quy trình của chúng tôi",
      title: "Cách Chúng tôi Triển khai",
      step1: { label: "Discovery", desc: "Hiểu sâu về business và pain points" },
      step2: { label: "Design", desc: "Thiết kế kiến trúc hệ thống phù hợp" },
      step3: { label: "Build", desc: "Xây dựng với agile sprints" },
      step4: { label: "Deploy", desc: "Triển khai và training team" },
      step5: { label: "Optimize", desc: "Theo dõi và cải thiện liên tục" },
    },
    techStack: {
      subtitle: "Công nghệ",
      title: "Tech Stack Chúng tôi Sử dụng",
      ai: { label: "AI & ML", items: ["GPT-4", "Claude", "LangChain", "Vector DB"] },
      backend: { label: "Backend", items: ["Python", "Node.js", "PostgreSQL", "Redis"] },
      frontend: { label: "Frontend", items: ["React", "TypeScript", "Tailwind", "Vite"] },
      platforms: { label: "Platforms", items: ["Odoo", "ERPNext", "Custom CRM", "AI Agents"] },
    },
    whatWeDo: {
      subtitle: "Năng lực Cốt lõi",
      title: "Chúng tôi làm gì",
      aiSystems: "Hệ thống AI",
      businessAuto: "Tự động hóa Doanh nghiệp",
      erpCrm: "ERP / CRM",
      digitalPlatforms: "Nền tảng Số",
      robotics: "Robotics & Agentic AI",
    },
    solutions: {
      subtitle: "Giải pháp của chúng tôi",
      title: "Hệ thống Chúng tôi Triển khai",
      learnMore: "Tìm hiểu thêm",
      crm: { label: "CRM", desc: "Hệ thống quản lý quan hệ khách hàng thông minh" },
      erp: { label: "ERP (Odoo / ERPNext)", desc: "Triển khai hoạch định nguồn lực doanh nghiệp" },
      dms: { label: "DMS", desc: "Hệ thống quản lý nhà phân phối" },
      pos: { label: "Hệ thống POS", desc: "Hạ tầng điểm bán hàng thông minh" },
      ecommerce: { label: "E-Commerce", desc: "Nền tảng thương mại điện tử" },
      cdc: { label: "CDC", desc: "Nền tảng dữ liệu khách hàng thống nhất" },
      aiAgents: { label: "AI Agents", desc: "Hệ thống AI tự động" },
    },
    projects: {
      subtitle: "Công việc của chúng tôi",
      title: "Hệ thống Chúng tôi Đã Triển khai",
      titleEnd: "",
      viewAll: "Xem tất cả dự án",
      project1: {
        title: "Triển khai CRM + AI cho Công ty Bất động sản",
        desc: "Hệ thống CRM tùy chỉnh với AI lead scoring",
        tech1: "CRM", tech2: "AI Agents", tech3: "Tự động hóa",
        metric1: "+280% Chuyển đổi", metric2: "-40% Công việc", metric3: "100% Phủ sóng",
      },
      project2: {
        title: "Triển khai Odoo ERP",
        desc: "ERP toàn diện với AI forecasting",
        tech1: "ERP", tech2: "Odoo", tech3: "AI",
        metric1: "+65% Độ chính xác", metric2: "-30% Tồn kho", metric3: "80% Tự động hóa",
      },
      project3: {
        title: "AI Finance Assistant",
        desc: "AI agents xử lý hóa đơn tự động",
        tech1: "AI", tech2: "OCR", tech3: "Automation",
        metric1: "-85% Thời gian", metric2: "<1% Lỗi", metric3: "Real-time",
      },
    },
    team: {
      subtitle: "Đội ngũ của chúng tôi",
      title: "Gặp gỡ",
      titleLine2: "Builders",
      titleLine3: "",
      description: "Đội ngũ builders, operators và engineers",
      meetTeam: "Gặp gỡ đội ngũ",
      member1: { name: "Minh Nguyen", role: "AI Engineer" },
      member2: { name: "Linh Tran", role: "System Architect" },
      member3: { name: "Khoa Pham", role: "Full-stack Developer" },
      member4: { name: "Hương Le", role: "Product Manager" },
    },
    experts: {
      subtitle: "Đội ngũ Chuyên gia",
      title: "Các Chuyên gia",
      description: "Đội ngũ chuyên gia giàu kinh nghiệm trong triển khai AI và hệ thống doanh nghiệp",
      meetTeam: "Tìm hiểu thêm về đội ngũ",
    },
    lab: {
      badge: "Ninja AI Lab",
      title: "Nơi",
      titleHighlight: "Builders Được Rèn luyện",
      description: "Tham gia lab và xây dựng hệ thống AI thực tế",
      exploreLab: "Khám phá Lab",
      realProjects: "100% Dự án Thực tế",
      realTeams: "Đội ngũ Chuyên nghiệp",
      realExecution: "Thực thi Thực tế",
      realImpact: "Tác động Đo lường được",
    },
    cta: {
      title: "Sẵn sàng xây dựng",
      titleHighlight: "tương lai?",
      description: "Hãy cùng chúng tôi tạo ra hệ thống AI",
      workWithUs: "Làm việc cùng chúng tôi",
      joinLab: "Tham gia Lab",
    },
  },
  solutions: {
    hero: {
      subtitle: "Giải pháp của chúng tôi",
      title: "Hệ thống",
      titleHighlight: "Chúng tôi Triển khai",
      description: "Từ CRM và ERP đến AI agents và tự động hóa toàn diện — chúng tôi triển khai hệ thống thực tế mang lại kết quả đo lường được.",
    },
    common: {
      discussSolution: "Thảo luận giải pháp",
      keyCapabilities: "Khả năng chính",
    },
    crm: {
      label: "CRM",
      tagline: "Quản lý Quan hệ Khách hàng",
      desc: "Hệ thống CRM thông minh với AI lead scoring, tự động hóa quy trình và phân tích real-time để tối ưu hóa chuyển đổi khách hàng.",
      feature1: "Quản lý Lead thông minh với AI scoring",
      feature2: "Tự động hóa quy trình bán hàng",
      feature3: "Dashboard và báo cáo real-time",
      feature4: "Tích hợp đa kênh (email, phone, chat)",
      feature5: "Dự đoán chuyển đổi và churn",
      tech1: "CRM Platform",
      tech2: "AI/ML",
      tech3: "Automation",
      tech4: "Analytics",
    },
    erp: {
      label: "ERP (Odoo / ERPNext)",
      tagline: "Hoạch định Nguồn lực Doanh nghiệp",
      desc: "Triển khai ERP toàn diện với Odoo hoặc ERPNext — tích hợp kế toán, kho, sản xuất, HR và AI forecasting.",
      feature1: "Kế toán và tài chính tự động",
      feature2: "Quản lý kho và chuỗi cung ứng",
      feature3: "Lập kế hoạch sản xuất với AI",
      feature4: "HR, Payroll và quản lý nhân sự",
      feature5: "Tích hợp đa chi nhánh",
      tech1: "Odoo",
      tech2: "ERPNext",
      tech3: "Python",
      tech4: "PostgreSQL",
    },
    dms: {
      label: "DMS",
      tagline: "Hệ thống Quản lý Nhà phân phối",
      desc: "Tối ưu hóa chuỗi phân phối với hệ thống quản lý nhà phân phối, theo dõi đơn hàng, kho và thanh toán real-time.",
      feature1: "Quản lý mạng lưới nhà phân phối",
      feature2: "Xử lý đơn hàng tự động",
      feature3: "Theo dõi kho và logistics",
      feature4: "Phân tích hiệu suất phân phối",
      feature5: "Tích hợp thanh toán và công nợ",
      tech1: "DMS Platform",
      tech2: "Mobile App",
      tech3: "Analytics",
      tech4: "Integration",
    },
    pos: {
      label: "Hệ thống POS",
      tagline: "Điểm Bán hàng Thông minh",
      desc: "Hạ tầng POS hiện đại với chế độ offline, tích hợp thanh toán, đồng bộ kho và báo cáo real-time.",
      feature1: "Chế độ offline hoàn toàn",
      feature2: "Tích hợp đa phương thức thanh toán",
      feature3: "Đồng bộ kho real-time",
      feature4: "Báo cáo và phân tích bán hàng",
      feature5: "Quản lý khuyến mãi và loyalty",
      tech1: "POS System",
      tech2: "Payment Gateway",
      tech3: "Cloud Sync",
      tech4: "Analytics",
    },
    ecommerce: {
      label: "E-Commerce",
      tagline: "Thương mại Điện tử",
      desc: "Nền tảng e-commerce có khả năng mở rộng với AI recommendations, quản lý kho tự động và tích hợp thanh toán.",
      feature1: "Storefront tùy chỉnh và responsive",
      feature2: "AI product recommendations",
      feature3: "Quản lý kho và fulfillment",
      feature4: "Tích hợp thanh toán đa kênh",
      feature5: "Marketing automation và SEO",
      tech1: "E-Commerce Platform",
      tech2: "AI/ML",
      tech3: "Payment Integration",
      tech4: "Analytics",
    },
    cdc: {
      label: "CDC",
      tagline: "Nền tảng Dữ liệu Khách hàng",
      desc: "Cái nhìn 360° về khách hàng với nền tảng dữ liệu thống nhất, phân khúc thông minh và phân tích hành vi.",
      feature1: "Thống nhất dữ liệu từ mọi nguồn",
      feature2: "Phân khúc khách hàng thông minh",
      feature3: "Phân tích hành vi và journey",
      feature4: "Tích hợp với marketing tools",
      feature5: "Privacy và compliance",
      tech1: "Data Platform",
      tech2: "ETL/ELT",
      tech3: "Analytics",
      tech4: "Integration",
      tech5: "Security",
    },
    aiAgents: {
      label: "AI Agents",
      tagline: "Hệ thống AI Tự động",
      desc: "Triển khai AI agents xử lý nhiệm vụ phức tạp — từ customer service, sales automation đến operations và analytics.",
      feature1: "AI Customer Service 24/7",
      feature2: "Sales và Lead qualification tự động",
      feature3: "Tự động hóa operations",
      feature4: "Phân tích và insights thông minh",
      feature5: "Tích hợp với hệ thống hiện có",
      tech1: "LLM (GPT-4, Claude)",
      tech2: "LangChain",
      tech3: "Vector DB",
      tech4: "Integration",
    },
    cta: {
      title: "Sẵn sàng triển khai?",
      description: "Hãy nói chuyện về cách chúng tôi có thể xây dựng hệ thống cho doanh nghiệp của bạn.",
      button: "Bắt đầu ngay",
    },
  },
  projects: {
    hero: {
      subtitle: "Dự án của chúng tôi",
      title: "Hệ thống",
      titleHighlight: "Chúng tôi Đã Triển khai",
      description: "Case studies thực tế về các hệ thống AI và automation chúng tôi đã xây dựng và triển khai cho khách hàng.",
    },
    project1: {
      title: "Triển khai CRM + AI cho Công ty Bất động sản",
      industry: "Bất động sản",
      tag1: "CRM", tag2: "AI Agents", tag3: "Tự động hóa",
      problemTitle: "Vấn đề",
      problem: "Công ty mất 60% leads do follow-up thủ công không kịp thời. Sales team quá tải với công việc admin.",
      solutionTitle: "Giải pháp",
      solution: "Triển khai CRM tùy chỉnh với AI lead scoring, tự động hóa follow-up và phân tích real-time.",
      tech1: "CRM Platform", tech2: "AI/ML", tech3: "Automation", tech4: "Analytics",
      resultsTitle: "Kết quả",
      result1: "+280% Tỷ lệ chuyển đổi Lead",
      result2: "-40% Công việc thủ công",
      result3: "3× Độ chính xác dự đoán",
      result4: "100% Phủ sóng follow-up",
    },
    project2: {
      title: "Triển khai Odoo ERP cho Nhà máy Sản xuất",
      industry: "Sản xuất",
      tag1: "ERP", tag2: "Odoo", tag3: "AI Forecasting",
      problemTitle: "Vấn đề",
      problem: "Tồn kho quá mức gây lỗ $200K/tháng. Không có visibility về production và supply chain.",
      solutionTitle: "Giải pháp",
      solution: "Triển khai Odoo ERP toàn diện với AI demand forecasting và tích hợp đa chi nhánh.",
      tech1: "Odoo ERP", tech2: "AI/ML", tech3: "Python", tech4: "PostgreSQL",
      resultsTitle: "Kết quả",
      result1: "+65% Độ chính xác dự báo",
      result2: "-30% Tồn kho",
      result3: "Real-time visibility toàn bộ",
      result4: "80% Tự động hóa quy trình",
    },
    project3: {
      title: "AI Finance Assistant - Tự động hóa Hóa đơn",
      industry: "Tài chính",
      tag1: "AI", tag2: "OCR", tag3: "Automation",
      problemTitle: "Vấn đề",
      problem: "Đội ngũ finance dành 70% thời gian xử lý hóa đơn thủ công. Tỷ lệ lỗi cao và chậm trễ.",
      solutionTitle: "Giải pháp",
      solution: "Triển khai AI agents với OCR để tự động đọc, phân loại và xử lý hóa đơn.",
      tech1: "GPT-4V", tech2: "OCR", tech3: "Python", tech4: "Automation",
      resultsTitle: "Kết quả",
      result1: "-85% Thời gian xử lý",
      result2: "<1% Tỷ lệ lỗi",
      result3: "Real-time reporting",
      result4: "Focus vào strategic work",
    },
    project4: {
      title: "E-Commerce Platform với AI Recommendations",
      industry: "Bán lẻ",
      tag1: "E-Commerce", tag2: "AI/ML", tag3: "Analytics",
      problemTitle: "Vấn đề",
      problem: "Tỷ lệ chuyển đổi thấp 1.2%. Khách hàng không tìm thấy sản phẩm phù hợp.",
      solutionTitle: "Giải pháp",
      solution: "Xây dựng nền tảng e-commerce với AI product recommendations và personalization.",
      tech1: "E-Commerce", tech2: "AI/ML", tech3: "React", tech4: "Analytics",
      resultsTitle: "Kết quả",
      result1: "+190% Tỷ lệ chuyển đổi",
      result2: "+45% Giá trị đơn hàng TB",
      result3: "-60% Tỷ lệ hết hàng",
      result4: "35% Doanh thu từ AI",
    },
    cta: {
      title: "Sẵn sàng hợp tác?",
      description: "Hãy nói chuyện về dự án tiếp theo của bạn.",
      button: "Liên hệ ngay",
    },
  },
  lab: {
    hero: {
      badge: "Innovation Lab",
      title: "Ninja AI Lab",
      subtitle: "Nơi Rèn Luyện AI Builders",
      description: "Ninja AI Lab là môi trường thực thi thực tế",
      cta: { primary: "Ứng tuyển tham gia Lab", secondary: "Tìm hiểu thêm" },
    },
    whatIsLab: {
      badge: "Lab là gì",
      title: "Môi trường",
      subtitle: "Thực thi Thực tế",
      description: "Nơi xây dựng hệ thống AI thực tế",
      details: "Builders làm việc cùng operators giàu kinh nghiệm",
      stats: {
        realProjects: { value: "100%", label: "Dự án Thực tế" },
        production: { value: "Live", label: "Hệ thống Production" },
        mentors: { value: "Expert", label: "Mentors & Operators" },
        outcomes: { value: "Proven", label: "Kết quả Builder" },
      },
    },
    whatNinjasDo: {
      badge: "Công việc",
      title: "Ninjas làm gì",
      build: "Xây dựng hệ thống AI thực tế",
      work: "Làm việc trên vấn đề thực tế",
      collaborate: "Hợp tác trong nhóm",
      deploy: "Triển khai giải pháp",
      alongside: "Làm việc cùng experts",
      ship: "Ship code production",
    },
    pillars: {
      badge: "Bạn nhận được gì",
      title: "4 Trụ cột Giá trị",
      knowledge: {
        label: "A. Kiến thức",
        desc: "Kiến thức thực tế về AI",
        points: ["AI system design", "Automation architecture", "Data pipeline", "LLM engineering"],
      },
      skills: {
        label: "B. Kỹ năng",
        desc: "Xây dựng sản phẩm thực tế",
        points: ["Build CRM systems", "Deploy ERP", "Create AI agents", "Solve challenges"],
      },
      environment: {
        label: "C. Môi trường",
        desc: "Môi trường hiệu suất cao",
        points: ["Mentor-guided sprints", "Team collaboration", "Code reviews", "Accountability culture"],
      },
      execution: {
        label: "D. Thực thi",
        desc: "Tham gia dự án thực",
        points: ["Live deployments", "Shipped products", "Real impact", "Business exposure"],
      },
    },
    projects: {
      badge: "Đầu ra Lab",
      title: "Hệ thống được xây dựng bởi Ninjas",
      by: "bởi",
      status: { production: "Production", live: "Live" },
      procurement: { title: "AI Procurement Agent", desc: "Agent tự động giám sát kho" },
      leadScoring: { title: "CRM Lead Scoring", desc: "ML model dự đoán chuyển đổi" },
      analytics: { title: "E-Commerce Analytics", desc: "Nền tảng phân tích real-time" },
      invoice: { title: "Invoice OCR Bot", desc: "Đọc hóa đơn tự động" },
    },
    cta: {
      title: "Sẵn sàng trở thành Ninja?",
      description: "Ứng tuyển tham gia lab",
      primary: "Ứng tuyển Lab",
      secondary: "Gặp gỡ Builders",
    },
  },
  about: {
    hero: {
      badge: "Về chúng tôi",
      title: "Chúng tôi Xây dựng Hệ thống",
      titleHighlight: "Mà Người khác Chỉ Nói về",
      description: "Ninja AI là công ty triển khai AI và phòng lab đổi mới có trụ sở tại Thành phố Hồ Chí Minh, Việt Nam. Chúng tôi tồn tại để thu hẹp khoảng cách giữa tiềm năng AI và kết quả kinh doanh thực tế.",
    },
    journey: {
      badge: "Câu chuyện của chúng tôi",
      title: "Hành trình Phát triển",
      chapter1: {
        number: "01",
        year: "2021",
        title: "Khởi đầu từ bài toán thật",
        subtitle: "Từ tư duy xây phần mềm → sang tư duy giải quyết vận hành",
        desc: "Ninja AI không bắt đầu từ việc 'làm thương hiệu AI', mà từ việc giải quyết các bài toán thật trong doanh nghiệp. Khởi điểm của chúng tôi là triển khai, va chạm, sửa lỗi, tối ưu và học từ thực tế.",
      },
      chapter2: {
        number: "02",
        year: "2022",
        title: "Khi hệ thống bắt đầu có chiều sâu",
        subtitle: "Từ triển khai đơn điểm → sang tư duy hệ thống tổng thể",
        desc: "Không chỉ làm hệ thống nữa, mà bắt đầu hiểu cách các lớp dữ liệu, quy trình và vận hành phải nối vào nhau. Mỗi lần triển khai là một lần học sâu hơn về cấu trúc doanh nghiệp. ERP đầu tiên, delivery thực chiến, kinh nghiệm tích lũy đa ngành.",
      },
      chapter3: {
        number: "03",
        year: "2023-2024",
        title: "Khi AI không còn là lớp phủ",
        subtitle: "Từ software-enabled → sang AI-enabled",
        desc: "AI không còn được xem là thứ trang trí thêm vào, mà trở thành một lớp năng lực mới trong hệ thống kinh doanh. Chúng tôi bắt đầu đưa AI vào chấm điểm CRM, báo cáo, tự động hóa dữ liệu và các luồng vận hành thật.",
      },
      chapter4: {
        number: "04",
        year: "2025",
        title: "Xây người, không chỉ xây hệ thống",
        subtitle: "Từ delivery team → sang ecosystem of builders",
        desc: "Không chỉ build solution, mà build builders. Ninja AI Lab ra đời để biến kiến thức thành năng lực triển khai thật. Mở lab, hình thành pipeline builder, mentoring, dự án nội bộ.",
      },
      chapter5: {
        number: "05",
        year: "2026+",
        title: "Viết tiếp chương AI-native enterprise",
        subtitle: "Từ triển khai giải pháp → sang kiến tạo năng lực tổ chức",
        desc: "Mục tiêu tiếp theo không chỉ là triển khai dự án, mà xây các doanh nghiệp có thể vận hành và tăng trưởng theo mô hình AI-native. Mở rộng khu vực, platform hóa, scale builder ecosystem.",
      },
    },
    mission: {
      title: "Sứ mệnh",
      description: "Triển khai hệ thống được hỗ trợ bởi AI để chuyển đổi cách thức hoạt động của doanh nghiệp — làm cho trí thông minh trở nên dễ tiếp cận, thực tế và có thể đo lường được cho các công ty trên khắp Đông Nam Á.",
    },
    vision: {
      title: "Tầm nhìn",
      description: "Một tương lai nơi mọi doanh nghiệp vừa và nhỏ ở Đông Nam Á hoạt động với cơ sở hạ tầng AI-native — và nơi thế hệ builders tiếp theo được rèn giũa thông qua thực thi thực tế.",
    },
    approach: {
      title: "Cách tiếp cận",
      description: "Chúng tôi làm việc cùng đội ngũ của bạn, hiểu hoạt động của bạn và triển khai các hệ thống thực sự được sử dụng. Không có dự án phình to. Không có lý thuyết. Chỉ có hệ thống hoạt động.",
    },
    culture: {
      title: "Môi trường Làm việc",
      subtitle: "Nơi chuyên nghiệp gặp gỡ sự thân thiện",
      celebration: "Lễ kỷ niệm",
      festival: "Sự kiện công ty",
      workspace: "Không gian làm việc",
      mentoring: "Mentoring",
      teamwork: "Làm việc nhóm",
    },
    videos: {
      title: "Đội ngũ Hành động",
      subtitle: "Những khoảnh khắc hợp tác và hỗ trợ",
    },
    values: {
      title: "Giá trị của chúng tôi",
      execution: {
        title: "Thực thi Trước tiên",
        desc: "Chúng tôi xây dựng và triển khai. Chiến lược không có thực thi là tiếng ồn.",
      },
      accountability: {
        title: "Trách nhiệm Thực sự",
        desc: "Chúng tôi sở hữu các triển khai của mình từ đầu đến cuối.",
      },
      systems: {
        title: "Tư duy Hệ thống",
        desc: "Chúng tôi thiết kế cho dài hạn với kiến trúc mô-đun.",
      },
      impact: {
        title: "Tác động Đo lường được",
        desc: "Mọi dự án đều có chỉ số thành công rõ ràng.",
      },
    },
    cta: {
      title: "Sẵn sàng Làm việc Cùng nhau?",
      description: "Cho dù bạn đang tìm kiếm đối tác triển khai AI hay muốn xây dựng bên trong lab của chúng tôi, chúng tôi đã sẵn sàng.",
      joinLab: "Tham gia Lab",
      viewProjects: "Xem Dự án",
    },
  },
  footer: {
    description: "Đối tác triển khai AI hàng đầu tại Đông Nam Á",
    quickLinks: "Khám phá",
    contact: "Liên hệ",
    newsletter: {
      title: "Newsletter",
      description: "Nhận insights về AI",
      placeholder: "Email của bạn",
    },
    legal: {
      privacy: "Chính sách bảo mật",
      terms: "Điều khoản",
      cookies: "Cookie Policy",
    },
    copyright: "Tất cả quyền được bảo lưu",
    tagline: "Xây dựng với ⚡ bởi Ninja AI",
  },
};
